### ISSUE TITLE
PHP 8.2 compatibility

### ISSUE THREAD

**Issue by iranimij** [ho-nl/magento2-ReachDigital_BetterIndexer#12]
Would you please compatible the repo with PHP 8.2?

**Comment by norgeindian** [comment]
@SimonPrins , now, this issue still makes it impossible to update to 2.4.7.
Would you be able to check that in the near future, or would you alternatively include a PR, if we find time on our own?

**Comment by SimonPrins** [comment]
I did a quick test and it looks like the module functions with PHP 8.2.
I have added PHP 8.2 compatibility in the `composer.json`.
If you run unto any issues, let me know.

**Comment by norgeindian** [comment]
@SimonPrins , awesome, thanks a lot. Will test it and come back to you, if I find anything problematic.
